### ISSUE TITLE
How to interpret the values?

### ISSUE THREAD

**Issue by javorosas** [sparkfun/Soil_Moisture_Sensor#3]
What are the ranges for this sensor? I would be really helpful to know how to interpret the analog values. What range of values should I get if I put it in a glass off water? What values for a completely dry soil? And what for wet soil?

Thanks.

**Comment by javorosas** [comment]
Something like this one

http://seeedstudio.com/wiki/Grove_-_Moisture_Sensor

**Comment by ToniCorinne** [comment]
Hi @javorosas - please take a look at the Soil Moisture Sensor [hookup guide](https://learn.sparkfun.com/tutorials/soil-moisture-sensor-hookup-guide). This includes some example code with example values for thresholds on wet and dry soil. You will need to calibrate your sensor for your particular soil supply, but the guide should help you get started.
